In [2]:
from pathlib import Path
import zipfile
import pandas as pd

from pathlib import Path

project_root = Path.cwd().parent

zip_path = project_root / "data" / "raw" / "2021-22-crdc-data.zip"
with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("SCH/Harassment and Bullying.csv") as f:
        df = pd.read_csv(f)

print(df.shape)
df.head()

(98010, 159)

/var/folders/r8/8pgq659n1c5db2p68_rcb9rh0000gn/T/ipykernel_86158/3773118893.py:12: DtypeWarning: Columns (0: LEAID, 1: COMBOKEY) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_HBALLEGATIONS_SEX,SCH_HBALLEGATIONS_ORI,...,SCH_HBDISCIPLINED_DIS_TR_M,SCH_HBDISCIPLINED_DIS_TR_F,TOT_HBDISCIPLINED_DIS_M,TOT_HBDISCIPLINED_DIS_F,SCH_HBDISCIPLINED_DIS_EL_M,SCH_HBDISCIPLINED_DIS_EL_F,SCH_HBDISCIPLINED_DIS_IDEA_M,SCH_HBDISCIPLINED_DIS_IDEA_F,SCH_HBDISCIPLINED_DIS_504_M,SCH_HBDISCIPLINED_DIS_504_F
0,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,10000299995,Yes,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,10000500870,No,2,0,...,0,0,0,0,0,0,0,0,0,0
2,AL,ALABAMA,100005,Albertville City,871,Albertville High School,10000500871,No,4,0,...,0,0,0,0,0,0,0,0,0,0
3,AL,ALABAMA,100005,Albertville City,879,Albertville Intermediate School,10000500879,No,1,0,...,0,0,0,0,0,0,0,0,0,0
4,AL,ALABAMA,100005,Albertville City,889,Albertville Elementary School,10000500889,No,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.head(15)

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_HBALLEGATIONS_SEX,SCH_HBALLEGATIONS_ORI,...,SCH_HBDISCIPLINED_DIS_TR_M,SCH_HBDISCIPLINED_DIS_TR_F,TOT_HBDISCIPLINED_DIS_M,TOT_HBDISCIPLINED_DIS_F,SCH_HBDISCIPLINED_DIS_EL_M,SCH_HBDISCIPLINED_DIS_EL_F,SCH_HBDISCIPLINED_DIS_IDEA_M,SCH_HBDISCIPLINED_DIS_IDEA_F,SCH_HBDISCIPLINED_DIS_504_M,SCH_HBDISCIPLINED_DIS_504_F
0,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,10000299995,Yes,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,10000500870,No,2,0,...,0,0,0,0,0,0,0,0,0,0
2,AL,ALABAMA,100005,Albertville City,871,Albertville High School,10000500871,No,4,0,...,0,0,0,0,0,0,0,0,0,0
3,AL,ALABAMA,100005,Albertville City,879,Albertville Intermediate School,10000500879,No,1,0,...,0,0,0,0,0,0,0,0,0,0
4,AL,ALABAMA,100005,Albertville City,889,Albertville Elementary School,10000500889,No,0,0,...,0,0,0,0,0,0,0,0,0,0
5,AL,ALABAMA,100005,Albertville City,1616,Albertville Kindergarten and PreK,10000501616,No,0,0,...,0,0,0,0,0,0,0,0,0,0
6,AL,ALABAMA,100005,Albertville City,2150,Albertville Primary School,10000502150,No,0,0,...,0,0,0,0,0,0,0,0,0,0
7,AL,ALABAMA,100006,Marshall County,193,Kate Duncan Smith DAR Middle,10000600193,No,0,0,...,0,0,0,0,0,0,0,0,0,0
8,AL,ALABAMA,100006,Marshall County,872,Asbury High School,10000600872,No,0,0,...,0,0,0,0,0,0,0,0,0,0
9,AL,ALABAMA,100006,Marshall County,877,Douglas Elementary School,10000600877,No,0,0,...,0,0,0,0,0,0,0,0,0,0
10,AL,ALABAMA,100006,Marshall County,878,Douglas High School,10000600878,No,0,1,...,0,0,0,0,0,0,0,0,0,0
11,AL,ALABAMA,100006,Marshall County,880,Brindlee Mountain Elementary School,10000600880,No,0,0,...,0,0,0,0,0,0,0,0,0,0
12,AL,ALABAMA,100006,Marshall County,883,Kate D Smith DAR High School,10000600883,No,0,0,...,0,0,0,0,0,0,0,0,0,0
13,AL,ALABAMA,100006,Marshall County,887,Brindlee Mountain Primary School,10000600887,No,0,0,...,0,0,0,0,0,0,0,0,0,0
14,AL,ALABAMA,100006,Marshall County,1413,Robert D Sloman Primary,10000601413,No,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
preview_cols = [
    "LEA_STATE",
    "LEA_STATE_NAME",
    "LEA_NAME",
    "SCH_NAME",
    "SCH_HBALLEGATIONS_SEX",
    "SCH_HBALLEGATIONS_RAC",
    "SCH_HBALLEGATIONS_DIS",
    "SCH_HBALLEGATIONS_REL",
    "SCH_HBALLEGATIONS_ORI"
]

df[preview_cols].head(15)

,LEA_STATE,LEA_STATE_NAME,LEA_NAME,SCH_NAME,SCH_HBALLEGATIONS_SEX,SCH_HBALLEGATIONS_RAC,SCH_HBALLEGATIONS_DIS,SCH_HBALLEGATIONS_REL,SCH_HBALLEGATIONS_ORI
0,AL,ALABAMA,Alabama Youth Services,AUTAUGA CAMPUS,0,0,0,0,0
1,AL,ALABAMA,Albertville City,Albertville Middle School,2,0,0,0,0
2,AL,ALABAMA,Albertville City,Albertville High School,4,1,0,0,0
3,AL,ALABAMA,Albertville City,Albertville Intermediate School,1,1,0,0,0
4,AL,ALABAMA,Albertville City,Albertville Elementary School,0,0,0,0,0
5,AL,ALABAMA,Albertville City,Albertville Kindergarten and PreK,0,0,0,0,0
6,AL,ALABAMA,Albertville City,Albertville Primary School,0,0,0,0,0
7,AL,ALABAMA,Marshall County,Kate Duncan Smith DAR Middle,0,0,0,0,0
8,AL,ALABAMA,Marshall County,Asbury High School,0,1,0,0,0
9,AL,ALABAMA,Marshall County,Douglas Elementary School,0,0,0,0,0
10,AL,ALABAMA,Marshall County,Douglas High School,0,0,0,0,1
11,AL,ALABAMA,Marshall County,Brindlee Mountain Elementary School,0,0,0,0,0
12,AL,ALABAMA,Marshall County,Kate D Smith DAR High School,0,0,0,0,0
13,AL,ALABAMA,Marshall County,Brindlee Mountain Primary School,0,0,0,0,0
14,AL,ALABAMA,Marshall County,Robert D Sloman Primary,0,0,0,0,0

In [5]:
response_preview = [
    "LEA_STATE",
    "LEA_NAME",
    "SCH_NAME",
    "TOT_HBDISCIPLINED_SEX_M",
    "TOT_HBDISCIPLINED_SEX_F",
    "TOT_HBDISCIPLINED_RAC_M",
    "TOT_HBDISCIPLINED_RAC_F",
    "TOT_HBDISCIPLINED_DIS_M",
    "TOT_HBDISCIPLINED_DIS_F"
]

df[response_preview].head(15)

,LEA_STATE,LEA_NAME,SCH_NAME,TOT_HBDISCIPLINED_SEX_M,TOT_HBDISCIPLINED_SEX_F,TOT_HBDISCIPLINED_RAC_M,TOT_HBDISCIPLINED_RAC_F,TOT_HBDISCIPLINED_DIS_M,TOT_HBDISCIPLINED_DIS_F
0,AL,Alabama Youth Services,AUTAUGA CAMPUS,0,0,0,0,0,0
1,AL,Albertville City,Albertville Middle School,2,0,0,0,0,0
2,AL,Albertville City,Albertville High School,2,1,1,0,0,0
3,AL,Albertville City,Albertville Intermediate School,2,0,2,2,0,0
4,AL,Albertville City,Albertville Elementary School,0,0,0,0,0,0
5,AL,Albertville City,Albertville Kindergarten and PreK,0,0,0,0,0,0
6,AL,Albertville City,Albertville Primary School,0,0,0,0,0,0
7,AL,Marshall County,Kate Duncan Smith DAR Middle,0,0,0,0,0,0
8,AL,Marshall County,Asbury High School,0,0,1,0,0,0
9,AL,Marshall County,Douglas Elementary School,0,0,0,0,0,0
10,AL,Marshall County,Douglas High School,0,0,0,0,0,0
11,AL,Marshall County,Brindlee Mountain Elementary School,0,0,0,0,0,0
12,AL,Marshall County,Kate D Smith DAR High School,0,0,0,0,0,0
13,AL,Marshall County,Brindlee Mountain Primary School,0,0,0,0,0,0
14,AL,Marshall County,Robert D Sloman Primary,0,0,0,0,0,0

In [6]:
from pathlib import Path
import zipfile

zip_path = Path("/Users/yoldaserdem/Downloads/capstone/Data_Bullying/2021-22-crdc-data.zip")

with zipfile.ZipFile(zip_path, "r") as z:
    for file in z.namelist():
        print(file)

LEA/Distance Education.csv
LEA/High School Equivalency Exam.csv
LEA/LEA Characteristics.csv
SCH/Advanced Mathematics.csv
SCH/Advanced Placement.csv
SCH/Algebra I.csv
SCH/Algebra II.csv
SCH/Biology.csv
SCH/Calculus.csv
SCH/Chemistry.csv
SCH/Computer Science.csv
SCH/Corporal Punishment.csv
SCH/COVID Directional Indicators.csv
SCH/Data Science.csv
SCH/Dual Enrollment.csv
SCH/Enrollment.csv
SCH/Expulsions.csv
SCH/Geometry.csv
SCH/Gifted and Talented.csv
SCH/Harassment and Bullying.csv
SCH/International Baccalaureate.csv
SCH/Internet Access and Devices.csv
SCH/Interscholastic Athletics.csv
SCH/Justice Facilities.csv
SCH/Offenses.csv
SCH/Physics.csv
SCH/Referrals and Arrests.csv
SCH/Restraint and Seclusion.csv
SCH/Retention.csv
SCH/SAT and ACT.csv
SCH/School Characteristics.csv
SCH/School Support.csv
SCH/Single Sex Classes.csv
SCH/Suspensions.csv
SCH/Transfers.csv

In [7]:
import pandas as pd

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("SCH/Suspensions.csv") as f:
        suspensions = pd.read_csv(f)

print(suspensions.shape)
suspensions.head()

(98010, 189)

/var/folders/r8/8pgq659n1c5db2p68_rcb9rh0000gn/T/ipykernel_86158/483172242.py:5: DtypeWarning: Columns (0: LEAID, 1: COMBOKEY) have mixed types. Specify dtype option on import or set low_memory=False.
  suspensions = pd.read_csv(f)

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_PSOOSINSTANCES_ALL,SCH_PSOOSINSTANCES_IDEA,...,SCH_DAYSMISSED_TR_M,SCH_DAYSMISSED_TR_F,TOT_DAYSMISSED_M,TOT_DAYSMISSED_F,SCH_DAYSMISSED_EL_M,SCH_DAYSMISSED_EL_F,SCH_DAYSMISSED_IDEA_M,SCH_DAYSMISSED_IDEA_F,SCH_DAYSMISSED_504_M,SCH_DAYSMISSED_504_F
0,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,10000299995,Yes,-9,-9,...,0,0,0,0,0,0,0,0,0,0
1,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,10000500870,No,-9,-9,...,9,9,231,142,104,38,21,13,0,1
2,AL,ALABAMA,100005,Albertville City,871,Albertville High School,10000500871,No,-9,-9,...,16,14,501,192,156,60,0,0,0,0
3,AL,ALABAMA,100005,Albertville City,879,Albertville Intermediate School,10000500879,No,-9,-9,...,3,9,134,61,47,28,0,8,4,0
4,AL,ALABAMA,100005,Albertville City,889,Albertville Elementary School,10000500889,No,-9,-9,...,0,0,9,0,3,0,3,0,0,0

In [8]:
suspensions.columns.tolist()

['LEA_STATE',
 'LEA_STATE_NAME',
 'LEAID',
 'LEA_NAME',
 'SCHID',
 'SCH_NAME',
 'COMBOKEY',
 'JJ',
 'SCH_PSOOSINSTANCES_ALL',
 'SCH_PSOOSINSTANCES_IDEA',
 'SCH_PSDISC_SINGOOS_HI_M',
 'SCH_PSDISC_SINGOOS_HI_F',
 'SCH_PSDISC_SINGOOS_AM_M',
 'SCH_PSDISC_SINGOOS_AM_F',
 'SCH_PSDISC_SINGOOS_AS_M',
 'SCH_PSDISC_SINGOOS_AS_F',
 'SCH_PSDISC_SINGOOS_HP_M',
 'SCH_PSDISC_SINGOOS_HP_F',
 'SCH_PSDISC_SINGOOS_BL_M',
 'SCH_PSDISC_SINGOOS_BL_F',
 'SCH_PSDISC_SINGOOS_WH_M',
 'SCH_PSDISC_SINGOOS_WH_F',
 'SCH_PSDISC_SINGOOS_TR_M',
 'SCH_PSDISC_SINGOOS_TR_F',
 'TOT_PSDISC_SINGOOS_M',
 'TOT_PSDISC_SINGOOS_F',
 'SCH_PSDISC_SINGOOS_EL_M',
 'SCH_PSDISC_SINGOOS_EL_F',
 'SCH_PSDISC_SINGOOS_IDEA_M',
 'SCH_PSDISC_SINGOOS_IDEA_F',
 'SCH_PSDISC_MULTOOS_HI_M',
 'SCH_PSDISC_MULTOOS_HI_F',
 'SCH_PSDISC_MULTOOS_AM_M',
 'SCH_PSDISC_MULTOOS_AM_F',
 'SCH_PSDISC_MULTOOS_AS_M',
 'SCH_PSDISC_MULTOOS_AS_F',
 'SCH_PSDISC_MULTOOS_HP_M',
 'SCH_PSDISC_MULTOOS_HP_F',
 'SCH_PSDISC_MULTOOS_BL_M',
 'SCH_PSDISC_MULTOOS_BL_F',
 'SCH_PSDISC_MULTOOS_WH_M',
 'SCH_PSDISC_MULTOOS_WH_F',
 'SCH_PSDISC_MULTOOS_TR_M',
 'SCH_PSDISC_MULTOOS_TR_F',
 'TOT_PSDISC_MULTOOS_M',
 'TOT_PSDISC_MULTOOS_F',
 'SCH_PSDISC_MULTOOS_EL_M',
 'SCH_PSDISC_MULTOOS_EL_F',
 'SCH_PSDISC_MULTOOS_IDEA_M',
 'SCH_PSDISC_MULTOOS_IDEA_F',
 'SCH_DISCWODIS_ISS_HI_M',
 'SCH_DISCWODIS_ISS_HI_F',
 'SCH_DISCWODIS_ISS_AM_M',
 'SCH_DISCWODIS_ISS_AM_F',
 'SCH_DISCWODIS_ISS_AS_M',
 'SCH_DISCWODIS_ISS_AS_F',
 'SCH_DISCWODIS_ISS_HP_M',
 'SCH_DISCWODIS_ISS_HP_F',
 'SCH_DISCWODIS_ISS_BL_M',
 'SCH_DISCWODIS_ISS_BL_F',
 'SCH_DISCWODIS_ISS_WH_M',
 'SCH_DISCWODIS_ISS_WH_F',
 'SCH_DISCWODIS_ISS_TR_M',
 'SCH_DISCWODIS_ISS_TR_F',
 'TOT_DISCWODIS_ISS_M',
 'TOT_DISCWODIS_ISS_F',
 'SCH_DISCWODIS_ISS_EL_M',
 'SCH_DISCWODIS_ISS_EL_F',
 'SCH_DISCWDIS_ISS_IDEA_HI_M',
 'SCH_DISCWDIS_ISS_IDEA_HI_F',
 'SCH_DISCWDIS_ISS_IDEA_AM_M',
 'SCH_DISCWDIS_ISS_IDEA_AM_F',
 'SCH_DISCWDIS_ISS_IDEA_AS_M',
 'SCH_DISCWDIS_ISS_IDEA_AS_F',
 'SCH_DISCWDIS_ISS_IDEA_HP_M',
 'SCH_DISCWDIS_ISS_IDEA_HP_F',
 'SCH_DISCWDIS_ISS_IDEA_BL_M',
 'SCH_DISCWDIS_ISS_IDEA_BL_F',
 'SCH_DISCWDIS_ISS_IDEA_WH_M',
 'SCH_DISCWDIS_ISS_IDEA_WH_F',
 'SCH_DISCWDIS_ISS_IDEA_TR_M',
 'SCH_DISCWDIS_ISS_IDEA_TR_F',
 'TOT_DISCWDIS_ISS_IDEA_M',
 'TOT_DISCWDIS_ISS_IDEA_F',
 'SCH_DISCWDIS_ISS_EL_M',
 'SCH_DISCWDIS_ISS_EL_F',
 'SCH_DISCWDIS_ISS_504_M',
 'SCH_DISCWDIS_ISS_504_F',
 'SCH_OOSINSTANCES_WODIS',
 'SCH_OOSINSTANCES_IDEA',
 'SCH_OOSINSTANCES_504',
 'SCH_DISCWODIS_SINGOOS_HI_M',
 'SCH_DISCWODIS_SINGOOS_HI_F',
 'SCH_DISCWODIS_SINGOOS_AM_M',
 'SCH_DISCWODIS_SINGOOS_AM_F',
 'SCH_DISCWODIS_SINGOOS_AS_M',
 'SCH_DISCWODIS_SINGOOS_AS_F',
 'SCH_DISCWODIS_SINGOOS_HP_M',
 'SCH_DISCWODIS_SINGOOS_HP_F',
 'SCH_DISCWODIS_SINGOOS_BL_M',
 'SCH_DISCWODIS_SINGOOS_BL_F',
 'SCH_DISCWODIS_SINGOOS_WH_M',
 'SCH_DISCWODIS_SINGOOS_WH_F',
 'SCH_DISCWODIS_SINGOOS_TR_M',
 'SCH_DISCWODIS_SINGOOS_TR_F',
 'TOT_DISCWODIS_SINGOOS_M',
 'TOT_DISCWODIS_SINGOOS_F',
 'SCH_DISCWODIS_SINGOOS_EL_M',
 'SCH_DISCWODIS_SINGOOS_EL_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_HI_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_HI_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_AM_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_AM_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_AS_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_AS_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_HP_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_HP_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_BL_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_BL_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_WH_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_WH_F',
 'SCH_DISCWDIS_SINGOOS_IDEA_TR_M',
 'SCH_DISCWDIS_SINGOOS_IDEA_TR_F',
 'TOT_DISCWDIS_SINGOOS_IDEA_M',
 'TOT_DISCWDIS_SINGOOS_IDEA_F',
 'SCH_DISCWDIS_SINGOOS_EL_M',
 'SCH_DISCWDIS_SINGOOS_EL_F',
 'SCH_DISCWDIS_SINGOOS_504_M',
 'SCH_DISCWDIS_SINGOOS_504_F',
 'SCH_DISCWODIS_MULTOOS_HI_M',
 'SCH_DISCWODIS_MULTOOS_HI_F',
 'SCH_DISCWODIS_MULTOOS_AM_M',
 'SCH_DISCWODIS_MULTOOS_AM_F',
 'SCH_DISCWODIS_MULTOOS_AS_M',
 'SCH_DISCWODIS_MULTOOS_AS_F',
 'SCH_DISCWODIS_MULTOOS_HP_M',
 'SCH_DISCWODIS_MULTOOS_HP_F',
 'SCH_DISCWODIS_MULTOOS_BL_M',
 'SCH_DISCWODIS_MULTOOS_BL_F',
 'SCH_DISCWODIS_MULTOOS_WH_M',
 'SCH_DISCWODIS_MULTOOS_WH_F',
 'SCH_DISCWODIS_MULTOOS_TR_M',
 'SCH_DISCWODIS_MULTOOS_TR_F',
 'TOT_DISCWODIS_MULTOOS_M',
 'TOT_DISCWODIS_MULTOOS_F',
 'SCH_DISCWODIS_MULTOOS_EL_M',
 'SCH_DISCWODIS_MULTOOS_EL_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_HI_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_HI_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_AM_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_AM_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_AS_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_AS_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_HP_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_HP_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_BL_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_BL_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_WH_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_WH_F',
 'SCH_DISCWDIS_MULTOOS_IDEA_TR_M',
 'SCH_DISCWDIS_MULTOOS_IDEA_TR_F',
 'TOT_DISCWDIS_MULTOOS_IDEA_M',
 'TOT_DISCWDIS_MULTOOS_IDEA_F',
 'SCH_DISCWDIS_MULTOOS_EL_M',
 'SCH_DISCWDIS_MULTOOS_EL_F',
 'SCH_DISCWDIS_MULTOOS_504_M',
 'SCH_DISCWDIS_MULTOOS_504_F',
 'SCH_DAYSMISSED_HI_M',
 'SCH_DAYSMISSED_HI_F',
 'SCH_DAYSMISSED_AM_M',
 'SCH_DAYSMISSED_AM_F',
 'SCH_DAYSMISSED_AS_M',
 'SCH_DAYSMISSED_AS_F',
 'SCH_DAYSMISSED_HP_M',
 'SCH_DAYSMISSED_HP_F',
 'SCH_DAYSMISSED_BL_M',
 'SCH_DAYSMISSED_BL_F',
 'SCH_DAYSMISSED_WH_M',
 'SCH_DAYSMISSED_WH_F',
 'SCH_DAYSMISSED_TR_M',
 'SCH_DAYSMISSED_TR_F',
 'TOT_DAYSMISSED_M',
 'TOT_DAYSMISSED_F',
 'SCH_DAYSMISSED_EL_M',
 'SCH_DAYSMISSED_EL_F',
 'SCH_DAYSMISSED_IDEA_M',
 'SCH_DAYSMISSED_IDEA_F',
 'SCH_DAYSMISSED_504_M',
 'SCH_DAYSMISSED_504_F']

In [9]:
import pandas as pd

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("SCH/Expulsions.csv") as f:
        Expulsions = pd.read_csv(f)

print(Expulsions.shape)
Expulsions.head()

(98010, 142)

/var/folders/r8/8pgq659n1c5db2p68_rcb9rh0000gn/T/ipykernel_86158/3013969504.py:5: DtypeWarning: Columns (0: LEAID, 1: COMBOKEY) have mixed types. Specify dtype option on import or set low_memory=False.
  Expulsions = pd.read_csv(f)

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_PSDISC_EXP_HI_M,SCH_PSDISC_EXP_HI_F,...,SCH_DISCWDIS_EXPZT_IDEA_WH_M,SCH_DISCWDIS_EXPZT_IDEA_WH_F,SCH_DISCWDIS_EXPZT_IDEA_TR_M,SCH_DISCWDIS_EXPZT_IDEA_TR_F,TOT_DISCWDIS_EXPZT_IDEA_M,TOT_DISCWDIS_EXPZT_IDEA_F,SCH_DISCWDIS_EXPZT_EL_M,SCH_DISCWDIS_EXPZT_EL_F,SCH_DISCWDIS_EXPZT_504_M,SCH_DISCWDIS_EXPZT_504_F
0,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,10000299995,Yes,-9,-9,...,0,0,0,0,0,0,0,0,0,0
1,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,10000500870,No,-9,-9,...,0,0,0,0,0,0,0,0,0,0
2,AL,ALABAMA,100005,Albertville City,871,Albertville High School,10000500871,No,-9,-9,...,0,0,0,0,0,0,0,0,0,0
3,AL,ALABAMA,100005,Albertville City,879,Albertville Intermediate School,10000500879,No,-9,-9,...,0,0,0,0,0,0,0,0,0,0
4,AL,ALABAMA,100005,Albertville City,889,Albertville Elementary School,10000500889,No,-9,-9,...,0,0,0,0,0,0,0,0,0,0

In [10]:
Expulsions.columns.tolist()

['LEA_STATE',
 'LEA_STATE_NAME',
 'LEAID',
 'LEA_NAME',
 'SCHID',
 'SCH_NAME',
 'COMBOKEY',
 'JJ',
 'SCH_PSDISC_EXP_HI_M',
 'SCH_PSDISC_EXP_HI_F',
 'SCH_PSDISC_EXP_AM_M',
 'SCH_PSDISC_EXP_AM_F',
 'SCH_PSDISC_EXP_AS_M',
 'SCH_PSDISC_EXP_AS_F',
 'SCH_PSDISC_EXP_HP_M',
 'SCH_PSDISC_EXP_HP_F',
 'SCH_PSDISC_EXP_BL_M',
 'SCH_PSDISC_EXP_BL_F',
 'SCH_PSDISC_EXP_WH_M',
 'SCH_PSDISC_EXP_WH_F',
 'SCH_PSDISC_EXP_TR_M',
 'SCH_PSDISC_EXP_TR_F',
 'TOT_PSDISC_EXP_M',
 'TOT_PSDISC_EXP_F',
 'SCH_PSDISC_EXP_EL_M',
 'SCH_PSDISC_EXP_EL_F',
 'SCH_PSDISC_EXP_IDEA_M',
 'SCH_PSDISC_EXP_IDEA_F',
 'SCH_DISCWODIS_EXPWE_HI_M',
 'SCH_DISCWODIS_EXPWE_HI_F',
 'SCH_DISCWODIS_EXPWE_AM_M',
 'SCH_DISCWODIS_EXPWE_AM_F',
 'SCH_DISCWODIS_EXPWE_AS_M',
 'SCH_DISCWODIS_EXPWE_AS_F',
 'SCH_DISCWODIS_EXPWE_HP_M',
 'SCH_DISCWODIS_EXPWE_HP_F',
 'SCH_DISCWODIS_EXPWE_BL_M',
 'SCH_DISCWODIS_EXPWE_BL_F',
 'SCH_DISCWODIS_EXPWE_WH_M',
 'SCH_DISCWODIS_EXPWE_WH_F',
 'SCH_DISCWODIS_EXPWE_TR_M',
 'SCH_DISCWODIS_EXPWE_TR_F',
 'TOT_DISCWODIS_EXPWE_M',
 'TOT_DISCWODIS_EXPWE_F',
 'SCH_DISCWODIS_EXPWE_EL_M',
 'SCH_DISCWODIS_EXPWE_EL_F',
 'SCH_DISCWDIS_EXPWE_IDEA_HI_M',
 'SCH_DISCWDIS_EXPWE_IDEA_HI_F',
 'SCH_DISCWDIS_EXPWE_IDEA_AM_M',
 'SCH_DISCWDIS_EXPWE_IDEA_AM_F',
 'SCH_DISCWDIS_EXPWE_IDEA_AS_M',
 'SCH_DISCWDIS_EXPWE_IDEA_AS_F',
 'SCH_DISCWDIS_EXPWE_IDEA_HP_M',
 'SCH_DISCWDIS_EXPWE_IDEA_HP_F',
 'SCH_DISCWDIS_EXPWE_IDEA_BL_M',
 'SCH_DISCWDIS_EXPWE_IDEA_BL_F',
 'SCH_DISCWDIS_EXPWE_IDEA_WH_M',
 'SCH_DISCWDIS_EXPWE_IDEA_WH_F',
 'SCH_DISCWDIS_EXPWE_IDEA_TR_M',
 'SCH_DISCWDIS_EXPWE_IDEA_TR_F',
 'TOT_DISCWDIS_EXPWE_IDEA_M',
 'TOT_DISCWDIS_EXPWE_IDEA_F',
 'SCH_DISCWDIS_EXPWE_EL_M',
 'SCH_DISCWDIS_EXPWE_EL_F',
 'SCH_DISCWDIS_EXPWE_504_M',
 'SCH_DISCWDIS_EXPWE_504_F',
 'SCH_DISCWODIS_EXPWOE_HI_M',
 'SCH_DISCWODIS_EXPWOE_HI_F',
 'SCH_DISCWODIS_EXPWOE_AM_M',
 'SCH_DISCWODIS_EXPWOE_AM_F',
 'SCH_DISCWODIS_EXPWOE_AS_M',
 'SCH_DISCWODIS_EXPWOE_AS_F',
 'SCH_DISCWODIS_EXPWOE_HP_M',
 'SCH_DISCWODIS_EXPWOE_HP_F',
 'SCH_DISCWODIS_EXPWOE_BL_M',
 'SCH_DISCWODIS_EXPWOE_BL_F',
 'SCH_DISCWODIS_EXPWOE_WH_M',
 'SCH_DISCWODIS_EXPWOE_WH_F',
 'SCH_DISCWODIS_EXPWOE_TR_M',
 'SCH_DISCWODIS_EXPWOE_TR_F',
 'TOT_DISCWODIS_EXPWOE_M',
 'TOT_DISCWODIS_EXPWOE_F',
 'SCH_DISCWODIS_EXPWOE_EL_M',
 'SCH_DISCWODIS_EXPWOE_EL_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_HI_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_HI_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_AM_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_AM_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_AS_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_AS_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_HP_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_HP_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_BL_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_BL_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_WH_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_WH_F',
 'SCH_DISCWDIS_EXPWOE_IDEA_TR_M',
 'SCH_DISCWDIS_EXPWOE_IDEA_TR_F',
 'TOT_DISCWDIS_EXPWOE_IDEA_M',
 'TOT_DISCWDIS_EXPWOE_IDEA_F',
 'SCH_DISCWDIS_EXPWOE_EL_M',
 'SCH_DISCWDIS_EXPWOE_EL_F',
 'SCH_DISCWDIS_EXPWOE_504_M',
 'SCH_DISCWDIS_EXPWOE_504_F',
 'SCH_DISCWODIS_EXPZT_HI_M',
 'SCH_DISCWODIS_EXPZT_HI_F',
 'SCH_DISCWODIS_EXPZT_AM_M',
 'SCH_DISCWODIS_EXPZT_AM_F',
 'SCH_DISCWODIS_EXPZT_AS_M',
 'SCH_DISCWODIS_EXPZT_AS_F',
 'SCH_DISCWODIS_EXPZT_HP_M',
 'SCH_DISCWODIS_EXPZT_HP_F',
 'SCH_DISCWODIS_EXPZT_BL_M',
 'SCH_DISCWODIS_EXPZT_BL_F',
 'SCH_DISCWODIS_EXPZT_WH_M',
 'SCH_DISCWODIS_EXPZT_WH_F',
 'SCH_DISCWODIS_EXPZT_TR_M',
 'SCH_DISCWODIS_EXPZT_TR_F',
 'TOT_DISCWODIS_EXPZT_M',
 'TOT_DISCWODIS_EXPZT_F',
 'SCH_DISCWODIS_EXPZT_EL_M',
 'SCH_DISCWODIS_EXPZT_EL_F',
 'SCH_DISCWDIS_EXPZT_IDEA_HI_M',
 'SCH_DISCWDIS_EXPZT_IDEA_HI_F',
 'SCH_DISCWDIS_EXPZT_IDEA_AM_M',
 'SCH_DISCWDIS_EXPZT_IDEA_AM_F',
 'SCH_DISCWDIS_EXPZT_IDEA_AS_M',
 'SCH_DISCWDIS_EXPZT_IDEA_AS_F',
 'SCH_DISCWDIS_EXPZT_IDEA_HP_M',
 'SCH_DISCWDIS_EXPZT_IDEA_HP_F',
 'SCH_DISCWDIS_EXPZT_IDEA_BL_M',
 'SCH_DISCWDIS_EXPZT_IDEA_BL_F',
 'SCH_DISCWDIS_EXPZT_IDEA_WH_M',
 'SCH_DISCWDIS_EXPZT_IDEA_WH_F',
 'SCH_DISCWDIS_EXPZT_IDEA_TR_M',
 'SCH_DISCWDIS_EXPZT_IDEA_TR_F',
 'TOT_DISCWDIS_EXPZT_IDEA_M',
 'TOT_DISCWDIS_EXPZT_IDEA_F',
 'SCH_DISCWDIS_EXPZT_EL_M',
 'SCH_DISCWDIS_EXPZT_EL_F',
 'SCH_DISCWDIS_EXPZT_504_M',
 'SCH_DISCWDIS_EXPZT_504_F']

In [11]:
for file in [
    "SCH/Harassment and Bullying.csv",
    "SCH/Suspensions.csv",
    "SCH/Expulsions.csv",
    "SCH/Referrals and Arrests.csv"
]:
    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(file) as f:
            temp = pd.read_csv(f, nrows=1)

    print("\n")
    print("="*80)
    print(file)
    print("="*80)

    for col in temp.columns:
        if "DISC" in col or "EXP" in col or "ARREST" in col or "REF" in col or "SUSP" in col:
            print(col)

================================================================================
SCH/Harassment and Bullying.csv
================================================================================
SCH_HBDISCIPLINED_SEX_HI_M
SCH_HBDISCIPLINED_SEX_HI_F
SCH_HBDISCIPLINED_SEX_AM_M
SCH_HBDISCIPLINED_SEX_AM_F
SCH_HBDISCIPLINED_SEX_AS_M
SCH_HBDISCIPLINED_SEX_AS_F
SCH_HBDISCIPLINED_SEX_HP_M
SCH_HBDISCIPLINED_SEX_HP_F
SCH_HBDISCIPLINED_SEX_BL_M
SCH_HBDISCIPLINED_SEX_BL_F
SCH_HBDISCIPLINED_SEX_WH_M
SCH_HBDISCIPLINED_SEX_WH_F
SCH_HBDISCIPLINED_SEX_TR_M
SCH_HBDISCIPLINED_SEX_TR_F
TOT_HBDISCIPLINED_SEX_M
TOT_HBDISCIPLINED_SEX_F
SCH_HBDISCIPLINED_SEX_EL_M
SCH_HBDISCIPLINED_SEX_EL_F
SCH_HBDISCIPLINED_SEX_IDEA_M
SCH_HBDISCIPLINED_SEX_IDEA_F
SCH_HBDISCIPLINED_SEX_504_M
SCH_HBDISCIPLINED_SEX_504_F
SCH_HBDISCIPLINED_RAC_HI_M
SCH_HBDISCIPLINED_RAC_HI_F
SCH_HBDISCIPLINED_RAC_AM_M
SCH_HBDISCIPLINED_RAC_AM_F
SCH_HBDISCIPLINED_RAC_AS_M
SCH_HBDISCIPLINED_RAC_AS_F
SCH_HBDISCIPLINED_RAC_HP_M
SCH_HBDISCIPLINED_RAC_HP_F
SCH_HBDISCIPLINED_RAC_BL_M
SCH_HBDISCIPLINED_RAC_BL_F
SCH_HBDISCIPLINED_RAC_WH_M
SCH_HBDISCIPLINED_RAC_WH_F
SCH_HBDISCIPLINED_RAC_TR_M
SCH_HBDISCIPLINED_RAC_TR_F
TOT_HBDISCIPLINED_RAC_M
TOT_HBDISCIPLINED_RAC_F
SCH_HBDISCIPLINED_RAC_EL_M
SCH_HBDISCIPLINED_RAC_EL_F
SCH_HBDISCIPLINED_RAC_IDEA_M
SCH_HBDISCIPLINED_RAC_IDEA_F
SCH_HBDISCIPLINED_RAC_504_M
SCH_HBDISCIPLINED_RAC_504_F
SCH_HBDISCIPLINED_DIS_HI_M
SCH_HBDISCIPLINED_DIS_HI_F
SCH_HBDISCIPLINED_DIS_AM_M
SCH_HBDISCIPLINED_DIS_AM_F
SCH_HBDISCIPLINED_DIS_AS_M
SCH_HBDISCIPLINED_DIS_AS_F
SCH_HBDISCIPLINED_DIS_HP_M
SCH_HBDISCIPLINED_DIS_HP_F
SCH_HBDISCIPLINED_DIS_BL_M
SCH_HBDISCIPLINED_DIS_BL_F
SCH_HBDISCIPLINED_DIS_WH_M
SCH_HBDISCIPLINED_DIS_WH_F
SCH_HBDISCIPLINED_DIS_TR_M
SCH_HBDISCIPLINED_DIS_TR_F
TOT_HBDISCIPLINED_DIS_M
TOT_HBDISCIPLINED_DIS_F
SCH_HBDISCIPLINED_DIS_EL_M
SCH_HBDISCIPLINED_DIS_EL_F
SCH_HBDISCIPLINED_DIS_IDEA_M
SCH_HBDISCIPLINED_DIS_IDEA_F
SCH_HBDISCIPLINED_DIS_504_M
SCH_HBDISCIPLINED_DIS_504_F


================================================================================
SCH/Suspensions.csv
================================================================================
SCH_PSDISC_SINGOOS_HI_M
SCH_PSDISC_SINGOOS_HI_F
SCH_PSDISC_SINGOOS_AM_M
SCH_PSDISC_SINGOOS_AM_F
SCH_PSDISC_SINGOOS_AS_M
SCH_PSDISC_SINGOOS_AS_F
SCH_PSDISC_SINGOOS_HP_M
SCH_PSDISC_SINGOOS_HP_F
SCH_PSDISC_SINGOOS_BL_M
SCH_PSDISC_SINGOOS_BL_F
SCH_PSDISC_SINGOOS_WH_M
SCH_PSDISC_SINGOOS_WH_F
SCH_PSDISC_SINGOOS_TR_M
SCH_PSDISC_SINGOOS_TR_F
TOT_PSDISC_SINGOOS_M
TOT_PSDISC_SINGOOS_F
SCH_PSDISC_SINGOOS_EL_M
SCH_PSDISC_SINGOOS_EL_F
SCH_PSDISC_SINGOOS_IDEA_M
SCH_PSDISC_SINGOOS_IDEA_F
SCH_PSDISC_MULTOOS_HI_M
SCH_PSDISC_MULTOOS_HI_F
SCH_PSDISC_MULTOOS_AM_M
SCH_PSDISC_MULTOOS_AM_F
SCH_PSDISC_MULTOOS_AS_M
SCH_PSDISC_MULTOOS_AS_F
SCH_PSDISC_MULTOOS_HP_M
SCH_PSDISC_MULTOOS_HP_F
SCH_PSDISC_MULTOOS_BL_M
SCH_PSDISC_MULTOOS_BL_F
SCH_PSDISC_MULTOOS_WH_M
SCH_PSDISC_MULTOOS_WH_F
SCH_PSDISC_MULTOOS_TR_M
SCH_PSDISC_MULTOOS_TR_F
TOT_PSDISC_MULTOOS_M
TOT_PSDISC_MULTOOS_F
SCH_PSDISC_MULTOOS_EL_M
SCH_PSDISC_MULTOOS_EL_F
SCH_PSDISC_MULTOOS_IDEA_M
SCH_PSDISC_MULTOOS_IDEA_F
SCH_DISCWODIS_ISS_HI_M
SCH_DISCWODIS_ISS_HI_F
SCH_DISCWODIS_ISS_AM_M
SCH_DISCWODIS_ISS_AM_F
SCH_DISCWODIS_ISS_AS_M
SCH_DISCWODIS_ISS_AS_F
SCH_DISCWODIS_ISS_HP_M
SCH_DISCWODIS_ISS_HP_F
SCH_DISCWODIS_ISS_BL_M
SCH_DISCWODIS_ISS_BL_F
SCH_DISCWODIS_ISS_WH_M
SCH_DISCWODIS_ISS_WH_F
SCH_DISCWODIS_ISS_TR_M
SCH_DISCWODIS_ISS_TR_F
TOT_DISCWODIS_ISS_M
TOT_DISCWODIS_ISS_F
SCH_DISCWODIS_ISS_EL_M
SCH_DISCWODIS_ISS_EL_F
SCH_DISCWDIS_ISS_IDEA_HI_M
SCH_DISCWDIS_ISS_IDEA_HI_F
SCH_DISCWDIS_ISS_IDEA_AM_M
SCH_DISCWDIS_ISS_IDEA_AM_F
SCH_DISCWDIS_ISS_IDEA_AS_M
SCH_DISCWDIS_ISS_IDEA_AS_F
SCH_DISCWDIS_ISS_IDEA_HP_M
SCH_DISCWDIS_ISS_IDEA_HP_F
SCH_DISCWDIS_ISS_IDEA_BL_M
SCH_DISCWDIS_ISS_IDEA_BL_F
SCH_DISCWDIS_ISS_IDEA_WH_M
SCH_DISCWDIS_ISS_IDEA_WH_F
SCH_DISCWDIS_ISS_IDEA_TR_M
SCH_DISCWDIS_ISS_IDEA_TR_F
TOT_DISCWDIS_ISS_IDEA_M
TOT_DISCWDIS_ISS_IDEA_F
SCH_DISCWDIS_ISS_EL_M
SCH_DISCWDIS_ISS_EL_F
SCH_DISCWDIS_ISS_504_M
SCH_DISCWDIS_ISS_504_F
SCH_DISCWODIS_SINGOOS_HI_M
SCH_DISCWODIS_SINGOOS_HI_F
SCH_DISCWODIS_SINGOOS_AM_M
SCH_DISCWODIS_SINGOOS_AM_F
SCH_DISCWODIS_SINGOOS_AS_M
SCH_DISCWODIS_SINGOOS_AS_F
SCH_DISCWODIS_SINGOOS_HP_M
SCH_DISCWODIS_SINGOOS_HP_F
SCH_DISCWODIS_SINGOOS_BL_M
SCH_DISCWODIS_SINGOOS_BL_F
SCH_DISCWODIS_SINGOOS_WH_M
SCH_DISCWODIS_SINGOOS_WH_F
SCH_DISCWODIS_SINGOOS_TR_M
SCH_DISCWODIS_SINGOOS_TR_F
TOT_DISCWODIS_SINGOOS_M
TOT_DISCWODIS_SINGOOS_F
SCH_DISCWODIS_SINGOOS_EL_M
SCH_DISCWODIS_SINGOOS_EL_F
SCH_DISCWDIS_SINGOOS_IDEA_HI_M
SCH_DISCWDIS_SINGOOS_IDEA_HI_F
SCH_DISCWDIS_SINGOOS_IDEA_AM_M
SCH_DISCWDIS_SINGOOS_IDEA_AM_F
SCH_DISCWDIS_SINGOOS_IDEA_AS_M
SCH_DISCWDIS_SINGOOS_IDEA_AS_F
SCH_DISCWDIS_SINGOOS_IDEA_HP_M
SCH_DISCWDIS_SINGOOS_IDEA_HP_F
SCH_DISCWDIS_SINGOOS_IDEA_BL_M
SCH_DISCWDIS_SINGOOS_IDEA_BL_F
SCH_DISCWDIS_SINGOOS_IDEA_WH_M
SCH_DISCWDIS_SINGOOS_IDEA_WH_F
SCH_DISCWDIS_SINGOOS_IDEA_TR_M
SCH_DISCWDIS_SINGOOS_IDEA_TR_F
TOT_DISCWDIS_SINGOOS_IDEA_M
TOT_DISCWDIS_SINGOOS_IDEA_F
SCH_DISCWDIS_SINGOOS_EL_M
SCH_DISCWDIS_SINGOOS_EL_F
SCH_DISCWDIS_SINGOOS_504_M
SCH_DISCWDIS_SINGOOS_504_F
SCH_DISCWODIS_MULTOOS_HI_M
SCH_DISCWODIS_MULTOOS_HI_F
SCH_DISCWODIS_MULTOOS_AM_M
SCH_DISCWODIS_MULTOOS_AM_F
SCH_DISCWODIS_MULTOOS_AS_M
SCH_DISCWODIS_MULTOOS_AS_F
SCH_DISCWODIS_MULTOOS_HP_M
SCH_DISCWODIS_MULTOOS_HP_F
SCH_DISCWODIS_MULTOOS_BL_M
SCH_DISCWODIS_MULTOOS_BL_F
SCH_DISCWODIS_MULTOOS_WH_M
SCH_DISCWODIS_MULTOOS_WH_F
SCH_DISCWODIS_MULTOOS_TR_M
SCH_DISCWODIS_MULTOOS_TR_F
TOT_DISCWODIS_MULTOOS_M
TOT_DISCWODIS_MULTOOS_F
SCH_DISCWODIS_MULTOOS_EL_M
SCH_DISCWODIS_MULTOOS_EL_F
SCH_DISCWDIS_MULTOOS_IDEA_HI_M
SCH_DISCWDIS_MULTOOS_IDEA_HI_F
SCH_DISCWDIS_MULTOOS_IDEA_AM_M
SCH_DISCWDIS_MULTOOS_IDEA_AM_F
SCH_DISCWDIS_MULTOOS_IDEA_AS_M
SCH_DISCWDIS_MULTOOS_IDEA_AS_F
SCH_DISCWDIS_MULTOOS_IDEA_HP_M
SCH_DISCWDIS_MULTOOS_IDEA_HP_F
SCH_DISCWDIS_MULTOOS_IDEA_BL_M
SCH_DISCWDIS_MULTOOS_IDEA_BL_F
SCH_DISCWDIS_MULTOOS_IDEA_WH_M
SCH_DISCWDIS_MULTOOS_IDEA_WH_F
SCH_DISCWDIS_MULTOOS_IDEA_TR_M
SCH_DISCWDIS_MULTOOS_IDEA_TR_F
TOT_DISCWDIS_MULTOOS_IDEA_M
TOT_DISCWDIS_MULTOOS_IDEA_F
SCH_DISCWDIS_MULTOOS_EL_M
SCH_DISCWDIS_MULTOOS_EL_F
SCH_DISCWDIS_MULTOOS_504_M
SCH_DISCWDIS_MULTOOS_504_F


================================================================================
SCH/Expulsions.csv
================================================================================
SCH_PSDISC_EXP_HI_M
SCH_PSDISC_EXP_HI_F
SCH_PSDISC_EXP_AM_M
SCH_PSDISC_EXP_AM_F
SCH_PSDISC_EXP_AS_M
SCH_PSDISC_EXP_AS_F
SCH_PSDISC_EXP_HP_M
SCH_PSDISC_EXP_HP_F
SCH_PSDISC_EXP_BL_M
SCH_PSDISC_EXP_BL_F
SCH_PSDISC_EXP_WH_M
SCH_PSDISC_EXP_WH_F
SCH_PSDISC_EXP_TR_M
SCH_PSDISC_EXP_TR_F
TOT_PSDISC_EXP_M
TOT_PSDISC_EXP_F
SCH_PSDISC_EXP_EL_M
SCH_PSDISC_EXP_EL_F
SCH_PSDISC_EXP_IDEA_M
SCH_PSDISC_EXP_IDEA_F
SCH_DISCWODIS_EXPWE_HI_M
SCH_DISCWODIS_EXPWE_HI_F
SCH_DISCWODIS_EXPWE_AM_M
SCH_DISCWODIS_EXPWE_AM_F
SCH_DISCWODIS_EXPWE_AS_M
SCH_DISCWODIS_EXPWE_AS_F
SCH_DISCWODIS_EXPWE_HP_M
SCH_DISCWODIS_EXPWE_HP_F
SCH_DISCWODIS_EXPWE_BL_M
SCH_DISCWODIS_EXPWE_BL_F
SCH_DISCWODIS_EXPWE_WH_M
SCH_DISCWODIS_EXPWE_WH_F
SCH_DISCWODIS_EXPWE_TR_M
SCH_DISCWODIS_EXPWE_TR_F
TOT_DISCWODIS_EXPWE_M
TOT_DISCWODIS_EXPWE_F
SCH_DISCWODIS_EXPWE_EL_M
SCH_DISCWODIS_EXPWE_EL_F
SCH_DISCWDIS_EXPWE_IDEA_HI_M
SCH_DISCWDIS_EXPWE_IDEA_HI_F
SCH_DISCWDIS_EXPWE_IDEA_AM_M
SCH_DISCWDIS_EXPWE_IDEA_AM_F
SCH_DISCWDIS_EXPWE_IDEA_AS_M
SCH_DISCWDIS_EXPWE_IDEA_AS_F
SCH_DISCWDIS_EXPWE_IDEA_HP_M
SCH_DISCWDIS_EXPWE_IDEA_HP_F
SCH_DISCWDIS_EXPWE_IDEA_BL_M
SCH_DISCWDIS_EXPWE_IDEA_BL_F
SCH_DISCWDIS_EXPWE_IDEA_WH_M
SCH_DISCWDIS_EXPWE_IDEA_WH_F
SCH_DISCWDIS_EXPWE_IDEA_TR_M
SCH_DISCWDIS_EXPWE_IDEA_TR_F
TOT_DISCWDIS_EXPWE_IDEA_M
TOT_DISCWDIS_EXPWE_IDEA_F
SCH_DISCWDIS_EXPWE_EL_M
SCH_DISCWDIS_EXPWE_EL_F
SCH_DISCWDIS_EXPWE_504_M
SCH_DISCWDIS_EXPWE_504_F
SCH_DISCWODIS_EXPWOE_HI_M
SCH_DISCWODIS_EXPWOE_HI_F
SCH_DISCWODIS_EXPWOE_AM_M
SCH_DISCWODIS_EXPWOE_AM_F
SCH_DISCWODIS_EXPWOE_AS_M
SCH_DISCWODIS_EXPWOE_AS_F
SCH_DISCWODIS_EXPWOE_HP_M
SCH_DISCWODIS_EXPWOE_HP_F
SCH_DISCWODIS_EXPWOE_BL_M
SCH_DISCWODIS_EXPWOE_BL_F
SCH_DISCWODIS_EXPWOE_WH_M
SCH_DISCWODIS_EXPWOE_WH_F
SCH_DISCWODIS_EXPWOE_TR_M
SCH_DISCWODIS_EXPWOE_TR_F
TOT_DISCWODIS_EXPWOE_M
TOT_DISCWODIS_EXPWOE_F
SCH_DISCWODIS_EXPWOE_EL_M
SCH_DISCWODIS_EXPWOE_EL_F
SCH_DISCWDIS_EXPWOE_IDEA_HI_M
SCH_DISCWDIS_EXPWOE_IDEA_HI_F
SCH_DISCWDIS_EXPWOE_IDEA_AM_M
SCH_DISCWDIS_EXPWOE_IDEA_AM_F
SCH_DISCWDIS_EXPWOE_IDEA_AS_M
SCH_DISCWDIS_EXPWOE_IDEA_AS_F
SCH_DISCWDIS_EXPWOE_IDEA_HP_M
SCH_DISCWDIS_EXPWOE_IDEA_HP_F
SCH_DISCWDIS_EXPWOE_IDEA_BL_M
SCH_DISCWDIS_EXPWOE_IDEA_BL_F
SCH_DISCWDIS_EXPWOE_IDEA_WH_M
SCH_DISCWDIS_EXPWOE_IDEA_WH_F
SCH_DISCWDIS_EXPWOE_IDEA_TR_M
SCH_DISCWDIS_EXPWOE_IDEA_TR_F
TOT_DISCWDIS_EXPWOE_IDEA_M
TOT_DISCWDIS_EXPWOE_IDEA_F
SCH_DISCWDIS_EXPWOE_EL_M
SCH_DISCWDIS_EXPWOE_EL_F
SCH_DISCWDIS_EXPWOE_504_M
SCH_DISCWDIS_EXPWOE_504_F
SCH_DISCWODIS_EXPZT_HI_M
SCH_DISCWODIS_EXPZT_HI_F
SCH_DISCWODIS_EXPZT_AM_M
SCH_DISCWODIS_EXPZT_AM_F
SCH_DISCWODIS_EXPZT_AS_M
SCH_DISCWODIS_EXPZT_AS_F
SCH_DISCWODIS_EXPZT_HP_M
SCH_DISCWODIS_EXPZT_HP_F
SCH_DISCWODIS_EXPZT_BL_M
SCH_DISCWODIS_EXPZT_BL_F
SCH_DISCWODIS_EXPZT_WH_M
SCH_DISCWODIS_EXPZT_WH_F
SCH_DISCWODIS_EXPZT_TR_M
SCH_DISCWODIS_EXPZT_TR_F
TOT_DISCWODIS_EXPZT_M
TOT_DISCWODIS_EXPZT_F
SCH_DISCWODIS_EXPZT_EL_M
SCH_DISCWODIS_EXPZT_EL_F
SCH_DISCWDIS_EXPZT_IDEA_HI_M
SCH_DISCWDIS_EXPZT_IDEA_HI_F
SCH_DISCWDIS_EXPZT_IDEA_AM_M
SCH_DISCWDIS_EXPZT_IDEA_AM_F
SCH_DISCWDIS_EXPZT_IDEA_AS_M
SCH_DISCWDIS_EXPZT_IDEA_AS_F
SCH_DISCWDIS_EXPZT_IDEA_HP_M
SCH_DISCWDIS_EXPZT_IDEA_HP_F
SCH_DISCWDIS_EXPZT_IDEA_BL_M
SCH_DISCWDIS_EXPZT_IDEA_BL_F
SCH_DISCWDIS_EXPZT_IDEA_WH_M
SCH_DISCWDIS_EXPZT_IDEA_WH_F
SCH_DISCWDIS_EXPZT_IDEA_TR_M
SCH_DISCWDIS_EXPZT_IDEA_TR_F
TOT_DISCWDIS_EXPZT_IDEA_M
TOT_DISCWDIS_EXPZT_IDEA_F
SCH_DISCWDIS_EXPZT_EL_M
SCH_DISCWDIS_EXPZT_EL_F
SCH_DISCWDIS_EXPZT_504_M
SCH_DISCWDIS_EXPZT_504_F


================================================================================
SCH/Referrals and Arrests.csv
================================================================================
SCH_DISCWODIS_REF_HI_M
SCH_DISCWODIS_REF_HI_F
SCH_DISCWODIS_REF_AM_M
SCH_DISCWODIS_REF_AM_F
SCH_DISCWODIS_REF_AS_M
SCH_DISCWODIS_REF_AS_F
SCH_DISCWODIS_REF_HP_M
SCH_DISCWODIS_REF_HP_F
SCH_DISCWODIS_REF_BL_M
SCH_DISCWODIS_REF_BL_F
SCH_DISCWODIS_REF_WH_M
SCH_DISCWODIS_REF_WH_F
SCH_DISCWODIS_REF_TR_M
SCH_DISCWODIS_REF_TR_F
TOT_DISCWODIS_REF_M
TOT_DISCWODIS_REF_F
SCH_DISCWODIS_REF_EL_M
SCH_DISCWODIS_REF_EL_F
SCH_DISCWDIS_REF_IDEA_HI_M
SCH_DISCWDIS_REF_IDEA_HI_F
SCH_DISCWDIS_REF_IDEA_AM_M
SCH_DISCWDIS_REF_IDEA_AM_F
SCH_DISCWDIS_REF_IDEA_AS_M
SCH_DISCWDIS_REF_IDEA_AS_F
SCH_DISCWDIS_REF_IDEA_HP_M
SCH_DISCWDIS_REF_IDEA_HP_F
SCH_DISCWDIS_REF_IDEA_BL_M
SCH_DISCWDIS_REF_IDEA_BL_F
SCH_DISCWDIS_REF_IDEA_WH_M
SCH_DISCWDIS_REF_IDEA_WH_F
SCH_DISCWDIS_REF_IDEA_TR_M
SCH_DISCWDIS_REF_IDEA_TR_F
TOT_DISCWDIS_REF_IDEA_M
TOT_DISCWDIS_REF_IDEA_F
SCH_DISCWDIS_REF_EL_M
SCH_DISCWDIS_REF_EL_F
SCH_DISCWDIS_REF_504_M
SCH_DISCWDIS_REF_504_F
SCH_DISCWODIS_ARR_HI_M
SCH_DISCWODIS_ARR_HI_F
SCH_DISCWODIS_ARR_AM_M
SCH_DISCWODIS_ARR_AM_F
SCH_DISCWODIS_ARR_AS_M
SCH_DISCWODIS_ARR_AS_F
SCH_DISCWODIS_ARR_HP_M
SCH_DISCWODIS_ARR_HP_F
SCH_DISCWODIS_ARR_BL_M
SCH_DISCWODIS_ARR_BL_F
SCH_DISCWODIS_ARR_WH_M
SCH_DISCWODIS_ARR_WH_F
SCH_DISCWODIS_ARR_TR_M
SCH_DISCWODIS_ARR_TR_F
TOT_DISCWODIS_ARR_M
TOT_DISCWODIS_ARR_F
SCH_DISCWODIS_ARR_EL_M
SCH_DISCWODIS_ARR_EL_F
SCH_DISCWDIS_ARR_IDEA_HI_M
SCH_DISCWDIS_ARR_IDEA_HI_F
SCH_DISCWDIS_ARR_IDEA_AM_M
SCH_DISCWDIS_ARR_IDEA_AM_F
SCH_DISCWDIS_ARR_IDEA_AS_M
SCH_DISCWDIS_ARR_IDEA_AS_F
SCH_DISCWDIS_ARR_IDEA_HP_M
SCH_DISCWDIS_ARR_IDEA_HP_F
SCH_DISCWDIS_ARR_IDEA_BL_M
SCH_DISCWDIS_ARR_IDEA_BL_F
SCH_DISCWDIS_ARR_IDEA_WH_M
SCH_DISCWDIS_ARR_IDEA_WH_F
SCH_DISCWDIS_ARR_IDEA_TR_M
SCH_DISCWDIS_ARR_IDEA_TR_F
TOT_DISCWDIS_ARR_IDEA_M
TOT_DISCWDIS_ARR_IDEA_F
SCH_DISCWDIS_ARR_EL_M
SCH_DISCWDIS_ARR_EL_F
SCH_DISCWDIS_ARR_504_M
SCH_DISCWDIS_ARR_504_F

In [12]:
for file in [
    "SCH/Suspensions.csv",
    "SCH/Expulsions.csv",
    "SCH/Referrals and Arrests.csv"
]:
    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(file) as f:
            temp = pd.read_csv(f, nrows=1)

    print("\n" + "="*80)
    print(file)
    print("="*80)

    for col in temp.columns:
        if any(x in col.upper() for x in ["HB", "BULL", "HARASS"]):
            print(col)

================================================================================
SCH/Suspensions.csv
================================================================================

================================================================================
SCH/Expulsions.csv
================================================================================

================================================================================
SCH/Referrals and Arrests.csv
================================================================================